title: Fred Rinaldo - Data Analytics Portfolio
description: Business Analytics | SQL | Power BI | Data Analysis

remote_theme: "jekyll/minima"

minima:
  skin: auto

header_pages:
  - index.md

show_excerpts: false

github_username: fredr11

plugins:
  - jekyll-feed
  

